name: Build and Push Docker Image

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/krtk:latest,ghcr.io/${{ github.repository_owner }}/krtk:master
          
      - name: Make package public
        run: |
          echo "Making package public"
          PACKAGE_NAME="krtk"
          PACKAGE_VISIBILITY="public"
          
          curl -X PATCH \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.GHCR_PAT }}" \
            "https://api.github.com/user/packages/container/${PACKAGE_NAME}/visibility" \
            -d '{"visibility":"'${PACKAGE_VISIBILITY}'"}'